name: GitHub Pages Deploy
run-name: GitHub Pages Deploy // ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 1 am
  push:
    branches:
      - main
      - dev/**
  workflow_dispatch:
    inputs:
      releaseToPages:
        description: 'Publish release to pages? (Y/N)'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      
      - name: Publish
        run: dotnet publish -c Release -o release
      

      # only run pages deploy when 'releaseToPages' is true
      - name: Upload pages artifact
        if: inputs.releaseToPages == true || github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./release/wwwroot
      
      - name: Deploy to GitHub Pages
        if: inputs.releaseToPages == true || github.ref_name == 'main'
        uses: actions/deploy-pages@v4